### ISSUE TITLE
Can't find or open executable

### ISSUE THREAD

**Issue by ELD** [Ragnaroek/kcov_docker#1]
I'm using your Docker container to attempt to run `kcov` locally and troubleshoot some test coverage woes. The executables have been built under macOS (which may be an issue unto itself) with the container being run on macOS as well. When I attempt to run the `kcov` executable pointed to the correct location, I get the error in the screenshot.

<img width="1680" alt="screen shot 2017-02-21 at 7 34 51 pm" src="https://cloud.githubusercontent.com/assets/650044/23194689/d7686878-f86c-11e6-977c-d7a4b6521405.png">
Why might this be happening?

**Comment by Ragnaroek** [comment]
Hi Eric,

if this executable (looks like a rust binary) is build for macOS it won't work in the kcov docker container. kcov needs to execute the binary and the docker images is based on a Ubuntu Linux.

In order to to use the kcov docker container you have to compile the binary for Linux (if its Rust, maybe with another docker container like https://github.com/jimmycuadra/docker-rust).

If you really need the executable as a macOS binary you have to compile kcov natively on your Mac.
Hope this helps,
Michael

**Comment by ELD** [comment]
Okay, I was wondering if that was part of the reason. Thanks for the help. I'll look into compiling the Rust binary in a Linux Docker container and then using your container for kcov.

Thanks!
